--8.1
SET ECHO OFF
SET FEEDBACK OFF
PROMPT Creating the MY_EMPLOYEE table. Please wait ...
CREATE TABLE my_employee
(id NUMBER(4) NOT NULL,
last_name VARCHAR2(25),
first_name VARCHAR2(25),
userid VARCHAR2(8),
salary NUMBER(9,2));
PROMPT Table MY_EMPLOYEE has been created
SET FEEDBACK ON
SET ECHO ON
insert INTO MY_EMPLOYEE
VALUES (1,'Patel', 'Ralph', 'rpatel', 795);
SELECT * from MY_EMPLOYEE;
COMMIT;
INSERT INTO MY_EMPLOYEE (USERID,FIRST_NAME,LAST_NAME,SALARY,ID)
VALUES ('bdancs','Betty','Dancs',860,2);
INSERT INTO  MY_EMPLOYEE
VALUES (3, 'Biri','Ben','bbiri', 1100);
INSERT INTO  MY_EMPLOYEE
VALUES (4, 'Newman','Chad','cnewman', 750);
INSERT INTO  MY_EMPLOYEE
VALUES (5, 'Ropeburn','Audrey','aropebur', 1550);
COMMIT;
-- nur Beispiel
DELETE MY_EMPLOYEE
WHERE id = 2;

--8.5
UPDATE MY_EMPLOYEE
SET LAST_NAME = 'Drexler';
SELECT * FROM MY_EMPLOYEE
rollback;
COMMIT;
UPDATE MY_EMPLOYEE
SET last_name = 'Drexler'
WHERE id = 3;
COMMIT;

--8.6
UPDATE MY_EMPLOYEE
SET salary = 1000
WHERE salary < 900;
COMMIT;

--8.7
DELETE MY_EMPLOYEE
WHERE first_name = 'Betty' AND last_name = 'Drexler';
COMMIT;

--8.8
DELETE MY_EMPLOYEE;
SELECT * FROM MY_EMPLOYEE;
DROP TABLE MY_EMPLOYEE;

--8.9
CREATE TABLE DEPARTMENT
(id NUMBER(7) PRIMARY KEY,
name VARCHAR2(25));

--8.10
INSERT INTO DEPARTMENT
SELECT deptno, dname
FROM dept;
SELECT * FROM DEPARTMENT;
COMMIT;
INSERT INTO DEPARTMENT
SELECT 50, 'Testabteilung'
from DUAL;
ROLLBACK;

--8.11
CREATE table EMPLOYEE 
as SELECT empno id, ename last_name, deptno dept_id
FROM EMP;
ALTER TABLE EMPLOYEE
add PRIMARY KEY (id);
ALTER TABLE EMPLOYEE
add FOREIGN KEY (dept_id) REFERENCES DEPARTMENT (id);
ALTER TABLE EMPLOYEE
DROP CONSTRAINT SYS_C00217053;
ALTER TABLE EMPLOYEE
add FOREIGN KEY (dept_id) REFERENCES DEPARTMENT (id) on DELETE CASCADE;

--8.12
CREATE SEQUENCE dept_id_seq
START with 60
INCREMENT by 10
MAXVALUE 200;

--8.13
INSERT INTO DEPARTMENT
VALUES (DEPT_ID_SEQ.nextval, 'Education');
INSERT INTO DEPARTMENT
VALUES (DEPT_ID_SEQ.nextval, 'Administration');
COMMIT;

--8.14
INSERT INTO EMPLOYEE
VALUES (8000, 'DOE', DEPT_ID_SEQ.currval);
INSERT INTO EMPLOYEE
VALUES (8001, 'DADA', DEPT_ID_SEQ.currval);
COMMIT;

--8.15
DELETE DEPARTMENT
WHERE id = 70;
COMMIT;

--8.16
CREATE VIEW emp_vu
as SELECT empno, ename employee, deptno
FROM emp;

--8.18
SELECT employee, deptno
FROM emp_vu;
